### ISSUE TITLE
[2.2] Finish LoFi wireframe on Figma

### ISSUE THREAD

**Issue by nicsng** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#10]
What is the task about? Finish the wireframe based on the requirements of the client.
Goals of the task: Finish the wireframe for LoFi.
Success/completion criteria: Finish the wireframe and update in report.
Allocated time: 4 days
Start date and end date of the issue/task: 2/09/23 - 5/09/23
Owner: Natalene, Karen
Status: Completed
Priority: Low

**Comment by hellolololol** [comment]
Comments:
Describe work done in detail: Finish the wireframe and update in report.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 2/09/23 - 5/09/23
