### ISSUE TITLE
[1.3.3] Activity diagram

### ISSUE THREAD

**Issue by hellolololol** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#11]
Task ID: 1.1.2
What is the task about? Start Activity diagram
Goals of the task: Shows the flow from one activity to another activity
Success/completion criteria: The diagram created and updated accurately and is inside M1 report.
Allocated time: 4 days
Start date and end date of the issue/task: 18/09/23 - 21/09/23
Owner: Xande
Status: Completed
Priority: High

**Comment by hellolololol** [comment]
Describe work done in detail: Drawing up the activity diagram on app.diagrams.net. The diagram outlines various steps and processes involved in a specific task/system, providing a visual aid. 
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 18/09/23 - 21/09/23

**Comment by adamxandria** [comment]
Describe work done in detail: Drawing up the activity diagram on app.diagrams.net. The diagram outlines the flow and processes of the Ferri management system. 
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 18/09/23 - 21/09/23

<img width="682" alt="Screenshot 2023-09-17 at 3 59 21 PM" src="https://github.com/nicsng/ICT2101-P11-6/assets/122199038/362d3c50-20e5-497a-b600-e22ce18a1f20">
