### ISSUE TITLE
tidy up minutes from meeting with client, and email to client by 13/09/23

### ISSUE THREAD

**Issue by nicsng** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#2]
Details:
Task title ID: #01
What is the task about?  Tidy up the minutes from the meeting with the client and email them by 13/09/23
Goals of the task: Update client on the minutes
Success/completion criteria: Email minutes to client
Allocated time: 6 days
Start date and end date of the issue/task: 08/09/23 - 13/09/23
Owner: All
Status: In progress
Priority: High

Comments:
Describe work done in detail:  Tidy up the minutes from the meeting with the client and email them to the client.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? If 
Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 08/09/23 - 13/09/23

**Comment by adamxandria** [comment]
Comments:
Describe work done in detail: Organised the meeting minutes, then promptly emailed them to the client, who subsequently responded with comments .

How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? If
Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 08/09/23 - 13/09/23

**Comment by adamxandria** [comment]
Comments:
Describe work done in detail: Organised the meeting minutes, then promptly emailed them to the client, who subsequently responded with comments .

How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? If
Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 08/09/23 - 13/09/23
