### ISSUE TITLE
[1.2.6] Develop Use Case Diagram

### ISSUE THREAD

**Issue by nicsng** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#3]
Details:
Task title ID: 2.1
What is the task about? Draft a use case diagram and show it to the client. Change it per client requirements.
Goals of the task: draft a use case diagram for the project.
Success/completion criteria: draft a use case diagram and show it to the client.
Allocated time: 3
Start date and end date of the issue/task: 11/09/23 - 14/09/23
Owner: Adam
Status: Completed
Priority: high

**Comment by nicsng** [comment]
d

**Comment by adamxandria** [comment]
Comments:
Describe work done in detail: Finish drafting use case diagram
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 11/09/23 - 14/09/23

**Comment by adamxandria** [comment]
Comments:
Describe work done in detail: Finish drafting use case diagram
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 11/09/23 - 14/09/23
