### ISSUE TITLE
[1.1.2] Define objectives and scope

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#33]
Task ID: 1.1.2
What is the task about? Defining the objectives and scope of our project
Goals of the task: Defining our objectives and scope of our project and get the whole team on the same page.
Success/completion criteria: The team understands our objectives and scope of our project and updating inside M1 Report.
Allocated time: 1 day
Start date and end date of the issue/task: 28/08/23 - 28/08/23
Owner: Xande
Status: Completed
Priority: High

**Comment by XandeK** [comment]
Describe work done in detail: Discussed and defined our objective and scope clearly and updated the report.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 28/08/23 - 28/08/23
