### ISSUE TITLE
[1.1.3] Research existing solutions

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#35]
Details:
What is the task about? Researching existing solutions
Goals of the task: Researching existing solutions
Success/completion criteria: Researching existing solutions.
Allocated time: 3 days
Start date and end date of the issue/task: 30/08/23 - 01/09/23
Owner: Khoo Xiaozhen Natalene
Status: Completed
Priority: low

**Comment by Natella-rex** [comment]
Comments:
Describe work done in detail: Researching existing solutions
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 30/08/23 - 01/09/23
