### ISSUE TITLE
[1.1.5] Meeting with client

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#36]
Details:
What is the task about? Meeting with client to clarify requirements and ask questions if any.
Goals of the task: Clarify requirements with clients.
Success/completion criteria: Clarify any doubts and questions with client during meeting.
Allocated time: 1 day
Start date and end date of the issue/task: 05/09/23 - 05/09/23
Owner: All
Status: Completed
Priority: High

**Comment by nicsng** [comment]
Comments:
Describe work done in detail: Clarifed any doubts and questions with the client during the meeting.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 05/09/23 - 05/09/23
