### ISSUE TITLE
[1.2.1] Define Functional Requirements

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#41]
Task ID: 1.2.1
What is the task about? Defining clearly the functional requirement of the project
Goals of the task: Clearly define the functional requirement based on the meeting with the client.
Success/completion criteria: The team agrees on the functional requirement and have updated the M1 report with the requirements.
Allocated time: 4 day
Start date and end date of the issue/task: 04/09/23 - 07/09/23
Owner: Xande
Status: Completed
Priority: High

**Comment by XandeK** [comment]
Describe work done in detail: Layout the functional requirements of the project based on the meeting with client and updated M1 report.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 04/09/23 - 07/09/23
