### ISSUE TITLE
[1.2.2] Define Non-Functional Requirements

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#42]
Details:
What is the task about? Define Non-Functional Requirements
Goals of the task: Define Non-Functional Requirements
Success/completion criteria: Define Non-Functional Requirements in report.
Allocated time: 3 days
Start date and end date of the issue/task: 06/09/23 - 08/09/23
Owner: Khoo Xiaozhen Natalene
Status: Completed
Priority: Medium

**Comment by Natella-rex** [comment]
Comments:
Describe work done in detail: Define Non-Functional Requirements in the report.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 06/09/23 - 08/09/23
