### ISSUE TITLE
[1.2.4] Define Safety and Security Requirements

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#43]
Details:
What is the task about?
Review of component diagram

Goals of the task:
Update of component diagram

Success/completion criteria:
Finish the safety and security requirement and update in M1 report

Allocated time: 1 day
Start date and end date of the issue/task: 7/9/23 - 8/9/23
Owner: Adam
Status: Complete
Priority: Low

**Comment by adamxandria** [comment]
Comments:
Describe work done in detail: Update and finish safety and security requirement
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 07/09/23 - 08/09/23
