### ISSUE TITLE
[1.2.5] Define User Interface Requirements

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#44]
Details:
What is the task about? Define user interface Requirements
Goals of the task: Define user interface Requirements
Success/completion criteria: Define user interface Requirements in report.
Allocated time: 2 days
Start date and end date of the issue/task: 11/09/23 - 12/09/23
Owner: Khoo Xiaozhen Natalene
Status: Completed
Priority: Medium

**Comment by Natella-rex** [comment]
Comments:
Describe work done in detail: Define user interface Requirements in the report.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 11/09/23 - 12/09/23
