### ISSUE TITLE
[1.3.1] Architecture design

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#46]
Task: Create an architecture design.
Task Description: Your objective is to develop an architecture design.
Task Goals: Incorporate the architecture design into the report.
Task Success Criteria: Ensure the performance requirements are finalized and updated in the report.
Time Allotted: 3 days
Task Dates: 14/09/23 - 15/09/23
Task Owner: Karen Goh
Task Status: Completed
Task Priority: Low

**Comment by hellolololol** [comment]
Comments:
Describe work done in detail: Created and revised the architecture design for the manager schedule page in the report.
How does the work affect the completion deadline: No impact.
Are there any changes to the success or completion criteria of the task? None.
Start date and end date of the work done for this comment: 14/09/23 - 15/09/23
