### ISSUE TITLE
[1.3.2] User Interface Design

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#47]
Details:
What is the task about? User Interface Design
Goals of the task: User Interface Design
Success/completion criteria: Update User Interface Design in report.
Allocated time: 3 days
Start date and end date of the issue/task: 18/09/23 - 20/09/23
Owner: Khoo Xiaozhen Natalene
Status: Completed
Priority: Medium

**Comment by Natella-rex** [comment]
Comments:
Describe work done in detail:  Update User Interface Design in report.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 18/09/23 - 20/09/23
