### ISSUE TITLE
[2.2] Simple sketch/ wireframe based on the requirements that has been concluded

### ISSUE THREAD

**Issue by nicsng** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#5]
Details:
Task title ID: #03
What is the task about? Create a simple wireframe based on the requirements of the client.
Goals of the task: Create a simple wireframe for the project.
Success/completion criteria: Create a simple wireframe for the project.
Allocated time: 2 days
Start date and end date of the issue/task: 09/09/23 - 10/09/23
Owner: Natalene, Karen
Status: Completed
Priority: Low

**Comment by hellolololol** [comment]
Comments:
Describe work done in detail: Create a simple wireframe design on Figma.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 09/09/23 - 10/09/23
