### ISSUE TITLE
[1.4.3] Create WBS

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#50]
Details:
What is the task about?
Create WBS

Goals of the task:
Finish WBS

Success/completion criteria:
Finish and update in M1 report

Allocated time: 1 day
Start date and end date of the issue/task: 15/9/23 - 16/9/23
Owner: Adam
Status: Complete
Priority: High

**Comment by adamxandria** [comment]
Comments:
Describe work done in detail: Created WBS
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 15/9/23 - 16/9/23
