### ISSUE TITLE
[1.4.4] Create Gantt Chart

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#51]
Task: Create a Gantt chart.
Task Description: Your objective is to develop a Gantt chart.
Task Goals: Incorporate the Gantt chart into the project plan.
Task Success Criteria: Ensure the project schedule is accurately represented in the Gantt chart.
Time Allotted: 2 days
Task Dates: 18/09/23 - 19/09/23
Task Owner: Karen Goh
Task Status: In Progress
Task Priority: Medium

**Comment by hellolololol** [comment]
Describe work done in detail: Created and revised the Gantt chart for the project schedule.
How does the work affect the completion deadline: No impact.
Are there any changes to the success or completion criteria of the task? None.
Start date and end date of the work done for this comment: 18/09/23 - 19/09/23
