### ISSUE TITLE
[1.5.1] Design Manager Dashboard Page

### ISSUE THREAD

**Issue by nicsng** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#52]
Details:
What is the task about? Design Manager Dashboard Page
Goals of the task: Design Manager Dashboard Page
Success/completion criteria: Update Design Manager Dashboard Page in report.
Allocated time: 1 day
Start date and end date of the issue/task: 18/09/23 - 18/09/23
Owner: Khoo Xiaozhen Natalene
Status: Completed
Priority: low

**Comment by Natella-rex** [comment]
Comments:
Describe work done in detail: Design Manager Dashboard Page in report.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 18/09/23 - 18/09/23
