### ISSUE TITLE
[1.5.3] Design Staff home page

### ISSUE THREAD

**Issue by nicsng** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#53]
Details:
What is the task about? Design Staff Home Page
Goals of the task: Design Staff Home Page
Success/completion criteria: Update Design Staff Home Page in report.
Allocated time: 1 day
Start date and end date of the issue/task: 19/09/23 - 19/09/23
Owner: Khoo Xiaozhen Natalene
Status: Completed
Priority: low

**Comment by Natella-rex** [comment]
Comments:
Describe work done in detail: Update Design Staff Home Page in report.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 19/09/23 - 19/09/23
