### ISSUE TITLE
[1.5.4] Design IT Admin Page

### ISSUE THREAD

**Issue by nicsng** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#54]
Task: Design Timetable Page.
Task Description: Your objective is to create a design for the IT Admin page.
Task Goals: Develop a visually appealing and functional design for the IT Admin page.
Task Success Criteria: Ensure that the timetable design meets usability and accessibility standards.
Time Allotted: 1 days
Task Dates: 19/09/23 - 19/09/23
Task Owner: Jonathan Chiu
Task Status: Completed
Task Priority: Medium

**Comment by ghost** [comment]
Comments:
Describe work done in detail: Created a design for the IT Admin Page
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 19/09/23 - 19/09/23
