### ISSUE TITLE
[1.5.5] Design timetable page

### ISSUE THREAD

**Issue by nicsng** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#55]
Task: Design Timetable Page.
Task Description: Your objective is to create a design for the timetable page.
Task Goals: Develop a visually appealing and functional design for the timetable page.
Task Success Criteria: Ensure that the timetable design meets usability and accessibility standards.
Time Allotted: 1 days
Task Dates: 19/09/23 - 19/09/23
Task Owner: Karen Goh
Task Status: Completed
Task Priority: Medium

**Comment by hellolololol** [comment]
Describe work done in detail: Created and revised the design for the timetable page in the report.
How does the work affect the completion deadline: No impact.
Are there any changes to the success or completion criteria of the task? None.
Start date and end date of the work done for this comment: 19/09/23 - 19/09/23
