### ISSUE TITLE
[1.6.2] Review Report

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#57]
Task ID: 1.6.2
What is the task about? Updating M1 report to ensure all information is accurate.
Goals of the task: Updating the M1 report to reflect all the information required for the submission.
Success/completion criteria: M1 report is fully completed with all the information required reflected in the report.
Allocated time: 4 day
Start date and end date of the issue/task: 18/09/23 - 21/09/23
Owner: Xande, Nicholas, Natalene
Status: Completed
Priority: High

**Comment by Natella-rex** [comment]
Comments:
Describe work done in detail: Review Report
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 19/09/23 - 21/09/23
