### ISSUE TITLE
[1.6.3] Submission of M1 Report

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#59]
Details:
What is the task about? Submission of M1 Report
Goals of the task: Submission of M1 Report
Success/completion criteria: Submission of M1 Report
Allocated time: 1 day
Start date and end date of the issue/task: 22/09/23 - 22/09/23
Owner: Xande
Status: Completed
Priority: Medium

**Comment by Natella-rex** [comment]
Comments:
Describe work done in detail: Submission of M1 Report
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 22/09/23 - 22/09/23
