### ISSUE TITLE
[2.2.2] Refine Non-Functional Requirement

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#61]
Details:
What is the task about? Review and update non-functional requirements based on comments from the M1 submission in the M2 report.
Goals of the task: Update non-functional requirements in the M2 report.
Success/completion criteria: Review and update non-functional requirements based on comments from the M1 submission in the M2 report.
Allocated time: 1 day
Start date and end date of the issue/task: 27/09/23 - 29/09/23
Owner: Nicholas
Status: Completed
Priority: Medium

**Comment by nicsng** [comment]
Comments:
Describe work done in detail: Reviewed and updated non-functional requirements based on comments from the M1 submission in the M2 report.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 27/09/23 - 29/09/23
