### ISSUE TITLE
[2.2.4] Refine Safety and Security Requirement

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#63]
Task: Refine Safety and Security Requirements.
Task Description: Your objective is to enhance safety and security requirements.
Task Goals: Improve the safety and security aspects in the report.
Task Success Criteria: Ensure that safety and security requirements are effectively refined and documented.
Time Allotted: 3 days
Task Dates: 3/10/23 - 5/10/23
Task Owner: Karen Goh
Task Status: Completed
Task Priority: Medium

**Comment by hellolololol** [comment]
Describe work done in detail: Enhanced and refined the safety and security requirements in the report.
How does the work affect the completion deadline: No impact.
Are there any changes to the success or completion criteria of the task? None.
Start date and end date of the work done for this comment: 3/10/23 - 5/10/23
