### ISSUE TITLE
[2.2.5] Refine User Interface Requirement

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#64]
Details:
What is the task about? Refine User Interface Requirement
Goals of the task: Refine User Interface Requirement
Success/completion criteria: Refine User Interface Requirement in report.
Allocated time: 3 days
Start date and end date of the issue/task: 04/10/23 - 06/10/23
Owner: Khoo Xiaozhen Natalene
Status: Completed
Priority: Medium

**Comment by Natella-rex** [comment]
Comments:
Describe work done in detail: Refine User Interface Requirement
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 04/10/23 - 06/10/23
