### ISSUE TITLE
[2.4.1] Report Documentation

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#67]
Details:
What is the task about? Update M2 report.
Goals of the task: Update and fill up the M2 report.
Success/completion criteria: Updated the M2 report.
Allocated time: 1 day
Start date and end date of the issue/task: 16/10/23 - 20/10/23
Owner: Nicholas, Xande, Natalene
Status: Completed
Priority: High

**Comment by nicsng** [comment]
Comments:
Describe work done in detail: Updated every section of M2 report inclusive of adding snippets of class, component, sequence diagram.
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 16/10/23 - 20/10/23
