### ISSUE TITLE
[2.1] Refining of Scope

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#68]
Details:
What is the task about? Refining of Scope
Goals of the task: Refining of Scope
Success/completion criteria: Update Refining of Scope in report.
Allocated time: 2 days
Start date and end date of the issue/task: 25/09/23 - 26/09/23
Owner: Khoo Xiaozhen Natalene
Status: Completed
Priority: low

**Comment by Natella-rex** [comment]
Comments:
Describe work done in detail: Refining of Scope
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment:  25/09/23 - 26/09/23
