### ISSUE TITLE
[2.4.3] Submission of M2 Report

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#70]
Details:
What is the task about?
Submit M2 report

Goals of the task:
Submit M2 report

Success/completion criteria:
Finish sending m2 report

Allocated time: 1 days
Start date and end date of the issue/task: 27/10/23 - 27/10/23
Owner: Adam
Status: Complete
Priority: High

**Comment by adamxandria** [comment]
Comments:
Describe work done in detail: submit M2 report
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 27/10/23 - 27/10/23
