### ISSUE TITLE
[2.3.3] Component Diagram

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#71]
Details:
What is the task about? Designing Component Diagram
Goals of the task: Complete Component Diagram
Success/completion criteria: Refine User Interface Requirement in report.
Allocated time: 3 days
Start date and end date of the issue/task: 16/10/23 - 18/10/23
Owner: Khoo Xiaozhen Natalene
Status: Completed
Priority: Medium

**Comment by Natella-rex** [comment]
Comments:
Describe work done in detail: Designing Component Diagram
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 16/10/23 - 18/10/23
