### ISSUE TITLE
[3.3.2] Review report

### ISSUE THREAD

**Issue by ghost** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#75]
Details:
What is the task about? Review M3 Report
Goals of the task: Review and adjust M3 Report
Success/completion criteria: Updated the M3 report.
Allocated time: 1 day
Start date and end date of the issue/task: 23/11/23 - 23/11/23
Owner: Xande, Nicholas. Natalene
Status: Completed
Priority: Medium

**Comment by XandeK** [comment]
Comments:
Describe work done in detail: review the report 
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 24/11/23 - 24/11/23
