### ISSUE TITLE
[3.2] Update use case diagram based on new requirements

### ISSUE THREAD

**Issue by nicsng** [nicsng/ICT2101-2201-Team-Project-Ferry-Company-#8]
Details:
What is the task about? Update the use case diagram based on new requirements

Goals of the task: Update the use case diagram based on new requirements
Success/completion criteria: Finish the use case diagram and update in report

Allocated time: 2 days
Start date and end date of the issue/task: 11/09/23 - 13/09/23
Owner: Adam, Nicholas
Status: In progress
Priority: Medium

**Comment by hellolololol** [comment]
Comments:
Describe work done in detail: Update the use case diagram based on new requirements
How does the work affect the completion deadline: NIL
Are there any changes to the success or completion criteria of the task? No
If Yes, please describe the details: NIL
Start date and end date of the work done for this comment: 11/09/23 - 13/09/23
